#!/usr/bin/perl

(@ARGV > 0 ) || &Usage;
(@ARGV < 3 ) || do{ print "Too many arguments\n"; &Usage;};

$ifile = $ARGV[0];
$ofile = $ARGV[1];

open( IN, "$ifile" ) || die "* Can't open ... $ifile";
open( OUT, "> $ofile" ) || die "* Can't open ... $ofile";

while( <IN> )  {
	print OUT $_;
	last if( /^total_frame/ );
}
$_ = <IN>;
print OUT $_;

while( <IN> )  {
	last if( /^-----/ );

	unless( /^(\d*): +([\.\d]*) +([\.\d]*)/ )  {
        print "* Unknown line ...\n$_\n";
        exit(1);
    }
	$n = $1;  $f0 = $2;  $pwr = $3;
	if( $f0 > 0 )  { $f0 += log( 2.0 ); }

	printf OUT "%d: %f %f\n", $n, $f0, $pwr;
}
print OUT $_;

close( IN );
close( OUT );



exit;
#------------------------------------------------------

sub Usage {
	print "MODIFY_F0 inputFile oututFile\n";
	exit;
}
