#!/usr/bin/perl

$input_text = "/tmp/gtalk$$.input";

$prog = "./gtalk";
$conf = "./ssm.conf";

&make_input_data();

$com = "$prog -C $conf < $input_text";
#print "$com\n";
system( $com );
unlink( $input_text );
exit;


sub make_input_data {
	open( OUT, "> $input_text" ) || die "Can't open ... $input_text";
	select( OUT );

	print OUT "prop Text.text = NoAutoOutput\n";
	print OUT "prop Text.pho = NoAutoOutput\n";
	print OUT "prop Text.dur = NoAutoOutput\n";
#	print OUT "set Log = CONSOLE\n";
#	print OUT "set Log = foo.log\n";
	print OUT "set Log.conf = YES\n";
	print OUT "set Log.text = YES\n";
	print OUT "set Log.arrangedText = YES\n";
	print OUT "set Log.chasen = YES\n";
	print OUT "set Log.tag = YES\n";
	print OUT "set Log.phoneme = YES\n";
	print OUT "set Log.mora = YES\n";
	print OUT "set Log.morph = YES\n";
	print OUT "set Log.aphrase = YES\n";
	print OUT "set Log.breath = YES\n";
	print OUT "set Log.sentence = YES\n";

#	print OUT "set File = data/sentence4.data\n";

#	print OUT "set Text = 私は音声合成器です。\n";
#	print OUT "set Text = 私は<SILENCE/>音声合成器です。\n";
#	print OUT "set Text = 私は<SILENCE MSEC=\"2000\"/>音声合成器です。\n";

#	print OUT "set Speaker = female01\n";
#	print OUT "set Text = 私は音声合成器です。\n";
#	print OUT "set Speaker = male02\n";
#	print OUT "set Text = <VOICE OPTIONAL=\"female01\">私は音声合成器です。</VOICE>\n";
#	print OUT "set Text = 彼女は、<VOICE OPTIONAL=\"female01\">私は音声合成器です。</VOICE>と言いました。\n";

#	print OUT "set Text = <VOICE ALPHA=\"0.3\">私は音声合成器です。</VOICE>\n";
#	print OUT "set Text = <VOICE ALPHA=\"0.6\">私は音声合成器です。</VOICE>\n";
#	print OUT "set Text = 彼女は、<VOICE OPTIONAL=\"female01\" ALPHA=\"0.6\">私は音声合成器です。</VOICE>と言いました。\n";

#	print OUT "set Text = 私は<RATE SPEED=\"2.0\">音声合成器</RATE>です。\n";
#	print OUT "set Text = 私は<VOLUME LEVEL=\"2.0\">音声</VOLUME>合成器です。\n";
#	print OUT "set Text = 私は<PITCH LEVEL=\"1.5\">音声</PITCH>合成器です。\n";
#	print OUT "set Text = 私は<PITCH RANGE=\"1.5\">音声</PITCH>合成器です。\n";

#	print OUT "set Text = 私は<EMPH>音声</EMPH>合成器です。\n";
#	print OUT "set Text = 行き先は<EMPH>京都</EMPH>です。\n";
#	print OUT "set Text = <EMPH>行き先が</EMPH>京都です。\n";


#	print OUT "set Text = 最寄り駅は南草津です。\n";
#	print OUT "set Text = 最寄り駅は<PRON SYM=\"ミナミク’サツ\">南草津</PRON>です。\n";
#	print OUT "set Text = 私はGtalkです。\n";
#	print OUT "set Text = 私は<PRON SYM=\"ジートーク\">Gtalk</PRON>です。\n";

#	print OUT "set Text = SMARTと書いて<SPELL>SMART</SPELL>と読みます。\n";
#	print OUT "set Text = 123です。\n";
#	print OUT "set Text = <SPELL>123</SPELL>です。\n";

#	print OUT "set Text = <CONTEXT TYPE=\"NUMBER\">123</CONTEXT>です。\n";
#	print OUT "set Text = <CONTEXT TYPE=\"DIGITS\">123</CONTEXT>です。\n";

#	print OUT "set Text = 今日は<CONTEXT TYPE=\"DATE\">2003-8-22</CONTEXT>です。\n";
#	print OUT "set Text = 今日は<CONTEXT TYPE=\"DATE\" DELIM=\"/\">2003/8/22</CONTEXT>です。\n";
#	print OUT "set Text = 今日は<CONTEXT TYPE=\"DATE\">2003/8/22</CONTEXT>です。\n";

#	print OUT "set Text = 時刻は<CONTEXT TYPE=\"TIME\">12:34</CONTEXT>です。\n";
#	print OUT "set Text = 時刻は<CONTEXT TYPE=\"TIME\">12:34:56</CONTEXT>です。\n";

#	print OUT "set Text = 電話番号は<CONTEXT TYPE=\"PHONE\">0120-123-4567</CONTEXT>です。\n";


	print OUT "set Text = この音声合成器は、タグを指定することにより、話すスピードを変えたり、声の高さを変えたり、声の大きさを変えたりすることができます。\n";

	print OUT "set Speak = NOW\n";

	print OUT "set Run = EXIT\n";
	close( OUT );
}


